### PR TITLE
Whitelist support

### PR DESCRIPTION
**Pull request by lstrojny**
This patch adds support to specify, which files exactly should be managed by assetic/require.js. This speeds up larger repositories, where external JS resources are fully bundled.

### CODE REVIEW

**Comment by lstrojny** [comment]
Forgot to mention: the patch is by @micxer, I only did some merging for him.

**Comment by lstrojny** [comment]
Ping, any news on this?

**Comment by lstrojny** [comment]
Sorry, didn’t mean to close it.

**Comment by ihortymoshenko** [comment]
@lstrojny, I don't see the need in this PR. If you think otherwise then let me know. I'm going to close this PR.

**Comment by lstrojny** [comment]
As stated above: this is very helpful in cases, where you bundle full repositories into your Resources folder. Assetic will than manage _all_ the included assets (tests, fixtures, whatever) which makes it very slow.

**Comment by ihortymoshenko** [comment]
@lstrojny, you can specify a concrete file or use `Bower` with `Grunt`. What about such approach?

**Comment by lstrojny** [comment]
Makes sense, yep.

**Pull request closed without merging**
