### PR TITLE
Almond integration fixed

### PR DESCRIPTION
**Pull request by guilhermeblanco**
This PR is a replacement of #52 by addressing required changes mentioned through comments on last commit (https://github.com/sfblaauw/HearsayRequireJSBundle/commit/29a12636a01e5c06b0ffbc353398cb8e6fe6b0db)

Hope this is enough to get this in faster. =D

### CODE REVIEW

**Comment by ihortymoshenko** [comment]
@guilhermeblanco, can you fix it https://travis-ci.org/hearsayit/HearsayRequireJSBundle/builds/20030420?

**Comment by guilhermeblanco** [comment]
@IgorTimoshenko fixed as per your request. Anything else missing? =)

**Comment by ihortymoshenko** [comment]
@guilhermeblanco, cool, thanks!

**Comment by guilhermeblanco** [comment]
@IgorTimoshenko thank you too!!! Don't forget also to look into my other one https://github.com/hearsayit/HearsayRequireJSBundle/pull/65

**Pull request merged**
