### PR TITLE
Added a check for request scope in getGlobals

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by ihortymoshenko** [comment]
@fixe, thanks for the contribution. Can you describe the case when these changes are needed? Thanks!

**Comment by fixe** [comment]
@IgorTimoshenko When using the Twig Environment from a Symfony2 command the getGlobals method are throwing an error because the request scope is inactive. Do you want me to add a test?

**Comment by ihortymoshenko** [comment]
@fixe, that will be great.

**Comment by mmucklo** [comment]
+1 on the fix as this breaks using instantiating getGlobals() from the symfony console.

```
  [Symfony\Component\DependencyInjection\Exception\InactiveScopeException]
  You cannot create a service ("templating.helper.assets") of an inactive scope ("request").
```

```
Exception trace:
 () at .../appEngDebugProjectContainer.php:11696
 appEngDebugProjectContainer->getTemplating_Helper_AssetsService() at .../app/bootstrap.php.cache:156
 Symfony\Component\DependencyInjection\Container->get() at .../vendor/hearsay/require-js-bundle/Hearsay/RequireJSBundle/Configuration/ConfigurationBuilder.php:115
 Hearsay\RequireJSBundle\Configuration\ConfigurationBuilder->getConfiguration() at .../vendor/hearsay/require-js-bundle/Hearsay/RequireJSBundle/Twig/Extension/RequireJSExtension.php:91
 Hearsay\RequireJSBundle\Twig\Extension\RequireJSExtension->getGlobals() at .../vendor/twig/twig/lib/Twig/Environment.php:1103
 Twig_Environment->initGlobals() at .../vendor/twig/twig/lib/Twig/Environment.php:1031
```

**Comment by ihortymoshenko** [comment]
@fixe, I cannot reproduce the issue. Can you describe the issue more detail? Thanks!

**Comment by fixe** [comment]
The issue is this: https://github.com/symfony/symfony/issues/4514

You can reproduce it by creating a Symfony Command that renders a template which initialises RequireJS.

**Comment by ihortymoshenko** [comment]
@fixe, I see. What do you do with a template which initialises RequireJS in Symfony command? I cannot imagine the case when does it needed.

**Comment by fixe** [comment]
@IgorTimoshenko, my case was using base.html.twig as base email template. What do you think we should do in this case?

**Comment by ihortymoshenko** [comment]
@fixe, did you use the `base.html.twig` template also as an initialize template? It's not a problem to add the proposed changes. I'm just want to understand all in order to prevent similar issue in the future.

**Comment by fixe** [comment]
@IgorTimoshenko, yes, I am using the `require_js_initialize` tag in my base.html.twig

**Comment by ihortymoshenko** [comment]
@fixe, I've again the code and I think we can just remove the `getGlobals` method. Would it be enough? What do you think?

**Comment by fixe** [comment]
@IgorTimoshenko: That works for me, thanks :)

**Comment by ihortymoshenko** [comment]
@fixe, you're welcome. Thanks you too for the contribution.

**Pull request closed without merging**
