### PR TITLE
Honour assets base url

### PR DESCRIPTION
**Pull request by Bendihossan**
Trying to fix this #19. Modified version of the solution from this PR #25.

@IgorTimoshenko - can you review this and check I've done the right thing? The tests now pass and I've also tried the code changes on a project I'm working on and it works as I would expect it to but I'm new to this bundle so would like your input.

### CODE REVIEW

**Comment by ihortymoshenko** [comment]
@Bendihossan, thanks for contribution. It looks like all works. If you also add the Unit tests for the case when the `assetic.use_controller` parameter is set to `false`, it will be great!

**Comment by Bendihossan** [comment]
@IgorTimoshenko I think that case is handled by `testRootUrlIgnoredIfAppropriate` where it passes `false` as the value for the ConfigurationBuilder's constructor for `$useControllerForAssets`:

`$builder = new ConfigurationBuilder($translator, $container, false, '/js');`

Is that what you meant or is there something else I can do?

**Comment by ihortymoshenko** [comment]
@Bendihossan, yes, you are right, merged.

**Comment by Bendihossan** [comment]
Thanks @IgorTimoshenko :)

**Pull request merged**
